POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "john1995",
  "password": "john95taggart"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "michaelson88",
  "password": "michael88son"
}