###
GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/persons/2

###
DELETE http://localhost:3001/api/blogs/2

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  
  "title": "Latest Updates: At Least 9 Dead as Ida Swamps New York City Area",
  "author": "John Taggart",
  "url": "https://www.nytimes.com/live/2021/09/02/nyregion/nyc-storm",
  "likes": 16
}